version: '3'
services:
  app:
    image: ${APP_IMAGE}
    stdin_open: true
    tty: true
    volumes:
      - .:/workspace
    environment:
      SETTINGS_PATH: /workspace/settings.yml
    ports:
      - 5000:5000
    command: >
      gunicorn --bind :5000 --config gunicorn.py --log-level debug --reload project.start
  db:
    image: mysql:5.7.26
    volumes:
      - ./db/init.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: app_db
    ports:
      - 3306:3306


# vi:et:ts=2:sw=2:cc=80
